### ISSUE TITLE
Setup automations for discord, github, and outlook

### ISSUE THREAD

**Issue by MFauzanAP** [QU-RoboSub/2025-general#14]
Automation ideas:

- For each subsystem, send updates for the following:
  - New commits
  - New issues
  - New issue comments

**Comment by MFauzanAP** [comment]
Discord channel for each subsystem which is open to anyone so others can get updated on what others are doing, they can mute it as well if it gets too annoying, maybe we can make it muted by default but idk if thats a thing on discord

**Comment by MFauzanAP** [comment]
You can listen to events on GitHub using webhooks, see [here](https://docs.github.com/en/webhooks/webhook-events-and-payloads#issue_comment). They even include data about the issue, so theoretically you can do something like this:

```js
// data obtained whenever the issue-comment event is sent
const payload = ...

// send update to each subsystem channel
payload.issue.labels.forEach((label) => {
  ...
});
```

**Comment by a-irhimeh** [comment]
Setup webhooks for each team + the general stuff

**Comment by a-irhimeh** [comment]
Tst new config

**Comment by MFauzanAP** [comment]
Currently this way all updates will be put in one channel, not sure if its the best idea bcs you cant mute notifs for a single subsystem

**Comment by a-irhimeh** [comment]
seems like it is very limited when it comes to what can be seperated

**Comment by MFauzanAP** [comment]
> seems like it is very limited when it comes to what can be seperated

If we want to separate the notifs I think we have no choice but to make a custom bot. If you've done coding with javascript before it wont be too difficult though. Check the following resources:

- [Discord.js getting started](https://discordjs.guide/)
- [Github webhooks for issue comment](**url**)

**Comment by a-irhimeh** [comment]
Sure I will see what I can do

**Comment by a-irhimeh** [comment]
How about this lets keep this for later and focus more on the important tasks I want to have something presentable by the end of eid week

**Comment by MFauzanAP** [comment]
> How about this lets keep this for later and focus more on the important tasks I want to have something presentable by the end of eid week

Sure no worries, this is P4 anyways, but if you think theres someone thats free to do this you can assign it to them to research

**Comment by MFauzanAP** [comment]
test
