### ISSUE TITLE
Keep track of agenda/points to update on for new member onboarding (Hazim)

### ISSUE THREAD

**Issue by MFauzanAP** [QU-RoboSub/2025-general#23]

**Comment by mombash** [comment]
I suggest that we can create some sort of formal onboarding that can be used to give the gist of the project to Hazim, but also be repurposed to be shown to other people like interested faculty, tiee, or even sponsors.

**Comment by MFauzanAP** [comment]
Let me know what you guys think of the following agenda. General list of things to mention and show:
- What is an AUV?
- What is the robosub competition about?
- The subsystem distribution
- Quickly go through the following (let them discover more on their own)
  - Discord and how its used as the main point of communication
  - Github, what we use it for, and how it works
  - Teams and what its used for
- Our current plan with the prototypes
- Where we are currently and what were working on

**Comment by Saad-Mohamed-Aden** [comment]
It is actually very good 
And this order of topics will make it easier for them to understand what is happening.
Also, we could reuse the slides that explained the robosub after adding those points to it
Then, these slides with the document would be used again for other people like interested faculty, tiee, or even sponsors.

**Comment by MFauzanAP** [comment]
No need for this anymore.
