### ISSUE TITLE
Add cable penetrators and routing to CAD

### ISSUE THREAD

**Issue by MFauzanAP** [QU-RoboSub/2025-general#35]

**Comment by a-irhimeh** [comment]
Completed initial plan of wiring between different waterproof compartments along with cable types and compatible penetrators

**Comment by MFauzanAP** [comment]
![Image](https://github.com/user-attachments/assets/53a8f0a4-6616-47df-be82-0149ee17407f)

@Saad-Mohamed-Aden added the cables and penetrators to the CAD file, color coded by the number of cores:
- 2 is pink
- 3 is blue
- 4 is green
