### ISSUE TITLE
Find AUVs or ROV online to purchase for testing

### ISSUE THREAD

**Issue by MoharramA** [QU-RoboSub/2025-general#56]
As requested by Dr.Meskin we need to search for a "small ROV or AUV for ordering so that you can some test before building our own AUV." Whatever anyone finds can be dumped onto discord and we can structure a better document to show the professors on thursday in shaa Allah.

**Comment by MFauzanAP** [comment]
what abt this one

![IMG-20240912-WA0007.jpg](https://github.com/user-attachments/assets/489e7c7e-7485-49f6-beeb-13fa94774f97)

**Comment by Suhib-Alsfarini** [comment]
Done, now we need to follow up with the TIEE
