### ISSUE TITLE
Update product requirements and constraints to cover all subsystems

### ISSUE THREAD

**Issue by MFauzanAP** [QU-RoboSub/2025-general#7]
Product Requirement - [link](https://qucloud.sharepoint.com/:w:/r/sites/MSDP-Newteam/Shared%20Documents/General/The-drive/Mechanical%20Team/Phase%20I%20-%20Product%20Definition/Product%20Requirements.docx?d=w1a966b1595b145f28595995db7dc2b0a&csf=1&web=1&e=DDsQIZ)

Design Constraints - [link](https://qucloud.sharepoint.com/:w:/r/sites/MSDP-Newteam/Shared%20Documents/General/The-drive/Mechanical%20Team/Phase%20I%20-%20Product%20Definition/Design%20Constraints.docx?d=w66c78b535495408098990e068137ac00&csf=1&web=1&e=vSKkKL)

**Comment by MFauzanAP** [comment]
@QU-RoboSub/electrical @QU-RoboSub/computer-engineering Please take a look at the [product requirements](https://qucloud.sharepoint.com/:w:/r/sites/MSDP-Newteam/Shared%20Documents/General/The-drive/General%20Files/Product%20Requirements.docx?d=w1a966b1595b145f28595995db7dc2b0a&csf=1&web=1&e=woPnpz), I've added some for your subsystems. Note that these **only contain requirements with numerical targets** so they can be put inside the House of Quality. The others will be put under the design constraints.

**Comment by a-irhimeh** [comment]
I just checked it out and made some changes in the mission control, computer vision, and acoustics and communication section. I just need @MoharramA or @mombash to review the acoustics part since this is a shared subsystem.

**Comment by MFauzanAP** [comment]
> I just checked it out and made some changes in the mission control, computer vision, and acoustics and communication section. I just need @MoharramA or @mombash to review the acoustics part since this is a shared subsystem.

I just took a look at the changes you've made, but actually we need to have numerical targets not qualitative ones. For example the "clear picture underwater" is hard to track and is subjective, meaning it'll be hard to measure. Either we can think of a quantitative value for it, or I think camera megapixels would be good enough tbh, and we can put "must provide clear pictures underwater" as a design constraint instead.

For the position triangulation, we can make a numeric target for it, for e.g it should calculate position with < 0.1m error or something. But I also think receiving range should be a specification that is tracked.

**Comment by MFauzanAP** [comment]
I'll be closing this as complete for now, we can come back to it later.
